from __future__ import annotations

import getpass
import os
import stat
from pathlib import Path
from typing import Callable

from .local_env import DEFAULT_LOCAL_ENV, load_local_env


_NON_SECRET_FIELDS = (
    ("NOEMA_KALSHI_ENV", "Kalshi environment", "demo"),
    ("KALSHI_API_KEY_ID", "Kalshi API key ID", ""),
    ("KALSHI_PRIVATE_KEY_PATH", "Kalshi private PEM path", ""),
    ("NOEMA_EVM_RPC_URL", "Dedicated EVM RPC URL", ""),
    ("NOEMA_EVM_ADDRESS", "Dedicated EVM public address", ""),
    ("NOEMA_FOUNDRY_ENDPOINT", "Microsoft Foundry/Azure OpenAI endpoint", ""),
    ("NOEMA_FOUNDRY_DEPLOYMENT", "Foundry model deployment name", ""),
    ("NOEMA_COGNITION_ENABLED", "Enable Foundry cognition (1/0)", "1"),
)

_SECRET_FIELDS = (
    ("NOEMA_FOUNDRY_API_KEY", "Foundry API key"),
)


def _clean(value: str) -> str:
    return value.strip()


def _quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def write_local_env(
    values: dict[str, str],
    *,
    path: str = DEFAULT_LOCAL_ENV,
) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Local NOEMA secrets/config. Never commit this file.",
        "# Generated by noema setup.",
        "",
    ]
    for key in sorted(values):
        lines.append(f"{key}={_quote(values[key])}")
    target.write_text("\n".join(lines) + "\n")
    target.chmod(stat.S_IRUSR | stat.S_IWUSR)
    return target


def run_setup_wizard(
    *,
    path: str = DEFAULT_LOCAL_ENV,
    input_fn: Callable[[str], str] = input,
    secret_fn: Callable[[str], str] = getpass.getpass,
) -> Path:
    existing = load_local_env(path)
    values = {**existing}

    print("NOEMA setup - leave a field blank to keep its current value.")

    for key, label, default in _NON_SECRET_FIELDS:
        current = os.getenv(key, existing.get(key, default))
        suffix = f" [{current}]" if current else ""
        entered = _clean(input_fn(f"{label}{suffix}: "))
        if entered:
            values[key] = entered
        elif current:
            values[key] = current

    for key, label in _SECRET_FIELDS:
        has_existing = bool(os.getenv(key, existing.get(key, "")))
        suffix = " [configured]" if has_existing else ""
        entered = _clean(secret_fn(f"{label}{suffix}: "))
        if entered:
            values[key] = entered
        elif has_existing:
            values[key] = os.getenv(key, existing.get(key, ""))

    target = write_local_env(values, path=path)
    print(f"Saved local configuration to {target}.")
    print("Run noema doctor next. Secrets are not printed by doctor.")
    return target
